/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LoadingSpinner {
    }
    interface SideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface StockFinder {
    }
    interface StockTicker {
        "stockSymbol": string;
    }
}
export interface StockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStockFinderElement;
}
declare global {
    interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {
    }
    var HTMLLoadingSpinnerElement: {
        prototype: HTMLLoadingSpinnerElement;
        new (): HTMLLoadingSpinnerElement;
    };
    interface HTMLSideDrawerElement extends Components.SideDrawer, HTMLStencilElement {
    }
    var HTMLSideDrawerElement: {
        prototype: HTMLSideDrawerElement;
        new (): HTMLSideDrawerElement;
    };
    interface HTMLStockFinderElement extends Components.StockFinder, HTMLStencilElement {
    }
    var HTMLStockFinderElement: {
        prototype: HTMLStockFinderElement;
        new (): HTMLStockFinderElement;
    };
    interface HTMLStockTickerElement extends Components.StockTicker, HTMLStencilElement {
    }
    var HTMLStockTickerElement: {
        prototype: HTMLStockTickerElement;
        new (): HTMLStockTickerElement;
    };
    interface HTMLElementTagNameMap {
        "loading-spinner": HTMLLoadingSpinnerElement;
        "side-drawer": HTMLSideDrawerElement;
        "stock-finder": HTMLStockFinderElement;
        "stock-ticker": HTMLStockTickerElement;
    }
}
declare namespace LocalJSX {
    interface LoadingSpinner {
    }
    interface SideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface StockFinder {
        "onStockSymbolSelected"?: (event: StockFinderCustomEvent<string>) => void;
    }
    interface StockTicker {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "loading-spinner": LoadingSpinner;
        "side-drawer": SideDrawer;
        "stock-finder": StockFinder;
        "stock-ticker": StockTicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "loading-spinner": LocalJSX.LoadingSpinner & JSXBase.HTMLAttributes<HTMLLoadingSpinnerElement>;
            "side-drawer": LocalJSX.SideDrawer & JSXBase.HTMLAttributes<HTMLSideDrawerElement>;
            "stock-finder": LocalJSX.StockFinder & JSXBase.HTMLAttributes<HTMLStockFinderElement>;
            "stock-ticker": LocalJSX.StockTicker & JSXBase.HTMLAttributes<HTMLStockTickerElement>;
        }
    }
}
